import Link from "next/link";
import SiteHeader from "@/components/layout/SiteHeader";
import SiteFooter from "@/components/layout/SiteFooter";

export const metadata = {
  title: "Showcase · AnyFigure",
  description: "Real figures generated by researchers using AnyFigure. CC-BY-shared examples for inspiration.",
};

interface Showcase {
  id: string;
  title: string;
  field: string;
  prompt: string;
  author?: string;
}

const SHOWCASES: Showcase[] = [
  { id: "1", title: "m6A regulation of MUC4 mRNA in PDAC", field: "Epigenomics", prompt: "METTL3 deposits m6A on MUC4 mRNA. IGF2BP1-3 readers stabilize the transcript. YTHDF2 promotes decay. Show normal vs overexpression.", author: "Demo" },
  { id: "2", title: "CD8+ T-cell exhaustion in tumor microenvironment", field: "Immuno-oncology", prompt: "Chronic antigen exposure drives CD8+ T-cell exhaustion through PD-1/TIM-3/LAG-3 co-expression and TOX-mediated transcriptional reprogramming.", author: "Demo" },
  { id: "3", title: "Wnt/β-catenin pathway with TCF/LEF targets", field: "Signaling", prompt: "Frizzled receptor activates Disheveled, inhibits GSK-3β, stabilizes β-catenin, which translocates and activates TCF/LEF transcription.", author: "Demo" },
  { id: "4", title: "CRISPR-Cas9 base editing schematic", field: "CRISPR", prompt: "dCas9-cytidine deaminase fusion converts C→T at the target site without DSB. Show gRNA + protospacer + edited window.", author: "Demo" },
  { id: "5", title: "Microbiome-tumor axis in CRC", field: "Microbiome", prompt: "F. nucleatum and pks+ E. coli colonize the colonic crypt, induce colibactin DNA damage, recruit MDSCs, and promote CRC progression.", author: "Demo" },
  { id: "6", title: "Insulin signaling cascade", field: "Metabolism", prompt: "Insulin binds IR, recruits IRS1/2, activates PI3K → Akt → mTOR and Akt → GSK-3 → glycogen synthesis. Show membrane + cytoplasm + nucleus.", author: "Demo" },
];

export default function ShowcasePage() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <SiteHeader />
      <main className="max-w-6xl mx-auto px-6 py-14">
        <div className="mb-12 text-center">
          <p className="text-[11px] uppercase tracking-wider text-teal-700 font-semibold mb-2">Showcase</p>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-3">Figures from real research.</h1>
          <p className="text-base text-slate-600 max-w-2xl mx-auto">
            A growing gallery of figures generated by AnyFigure users (shared under CC-BY with permission).
            Click any to open the underlying prompt in the editor.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {SHOWCASES.map((s) => (
            <div key={s.id} className="rounded-2xl border border-slate-200 bg-white overflow-hidden hover:border-slate-300 hover:shadow-md transition-all group">
              <div className="aspect-video bg-gradient-to-br from-teal-50 via-white to-indigo-50 flex items-center justify-center text-teal-700">
                <svg className="w-12 h-12 opacity-40" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.4">
                  <rect x="6" y="10" width="36" height="28" rx="2" />
                  <circle cx="16" cy="22" r="3" /><circle cx="32" cy="22" r="3" />
                  <path d="M19 22h10M24 25v6M18 31h12" strokeLinecap="round" />
                </svg>
              </div>
              <div className="p-4">
                <span className="inline-block text-[10px] font-semibold px-2 py-0.5 rounded bg-teal-100 text-teal-800 mb-2">
                  {s.field}
                </span>
                <h3 className="text-sm font-semibold text-slate-900 mb-1 leading-snug group-hover:text-teal-700">{s.title}</h3>
                <p className="text-[11px] text-slate-600 line-clamp-2 leading-relaxed">{s.prompt}</p>
                <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100">
                  <span className="text-[10px] text-slate-500">{s.author}</span>
                  <Link
                    href={`/?prompt=${encodeURIComponent(s.prompt)}`}
                    className="text-[11px] font-semibold text-teal-700 hover:underline"
                  >
                    Try this prompt →
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 rounded-3xl bg-slate-900 text-white p-10 text-center">
          <h2 className="text-2xl font-semibold mb-3">Want to be featured?</h2>
          <p className="text-slate-300 max-w-xl mx-auto mb-5 text-sm">
            Share a figure you generated, tag <span className="font-mono text-teal-300">@anyfigure</span> with a CC-BY licence,
            and we&apos;ll add it to the gallery with full credit.
          </p>
          <Link href="/contact?submit=showcase" className="inline-block px-5 py-2 rounded-full bg-white text-slate-900 font-semibold text-sm hover:bg-slate-100">
            Submit a figure
          </Link>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
